"""initial schema

Revision ID: 0001_initial
Revises: 
Create Date: 2026-07-14 14:48:59.114758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001_initial'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    op.create_table('auth_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('auth_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auth_tokens_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_auth_tokens_token'), ['token'], unique=True)
        batch_op.create_index(batch_op.f('ix_auth_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('recipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('time_minutes', sa.Integer(), nullable=False),
    sa.Column('cuisine', sa.String(length=80), nullable=False),
    sa.Column('difficulty', sa.String(length=40), nullable=False),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('ingredients', sa.Text(), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('external_id', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recipes_cuisine'), ['cuisine'], unique=False)
        batch_op.create_index(batch_op.f('ix_recipes_external_id'), ['external_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recipes_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recipes_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_recipes_owner_id'), ['owner_id'], unique=False)

    op.create_table('meal_plan_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('plan_date', sa.String(length=10), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.Column('custom_message', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('meal_plan_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meal_plan_entries_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_meal_plan_entries_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_meal_plan_entries_plan_date'), ['plan_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_meal_plan_entries_recipe_id'), ['recipe_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meal_plan_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meal_plan_entries_recipe_id'))
        batch_op.drop_index(batch_op.f('ix_meal_plan_entries_plan_date'))
        batch_op.drop_index(batch_op.f('ix_meal_plan_entries_owner_id'))
        batch_op.drop_index(batch_op.f('ix_meal_plan_entries_id'))

    op.drop_table('meal_plan_entries')
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recipes_owner_id'))
        batch_op.drop_index(batch_op.f('ix_recipes_name'))
        batch_op.drop_index(batch_op.f('ix_recipes_id'))
        batch_op.drop_index(batch_op.f('ix_recipes_external_id'))
        batch_op.drop_index(batch_op.f('ix_recipes_cuisine'))

    op.drop_table('recipes')
    with op.batch_alter_table('auth_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auth_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_auth_tokens_token'))
        batch_op.drop_index(batch_op.f('ix_auth_tokens_id'))

    op.drop_table('auth_tokens')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
